### ISSUE TITLE
第四題

### ISSUE THREAD

**Issue by alvinzhan** [NCU-CSIE-Algorithmics-A-1061/Homework-1#1]
## 第九組負責

**Comment by jeremy1320** [comment]
把 x-y 的值存到一個二維陣列，例：a[i,j] = x[i] - y[j]。
再將所有二維陣列裡的值取絕對值，之後找出二維陣列裡的最小值。
by 第九組

**Comment by c910335** [comment]
這做法看起來是 O(mn)
還有更快的做法
再想想看吧

**Comment by jeremy1320** [comment]
利用 while 迴圈（條件：i < m && j < n）。
先從 i = 0, j = 0 開始，將 x[i], y[j] 大的減小的存入 min。
再將小的一往下一個，例：若 x[i] < y[j]，i++。
做到結束，若出現小於 min 的數，則取代。
中間若出現 x[i] = y[j]，則 min = 0，直接跳出迴圈結束。
by 第九組

**Comment by c910335** [comment]
那麼你如何分析這個演算法的時間呢？

**Comment by jeremy1320** [comment]
平均下來，一個 m 會跟兩個 n 比到，一個 n 會跟兩個 m 比到。
所以時間複雜度應該是 (2m + 2n) / 2 = m + n。

**Comment by scps940707** [comment]
這位同學，要不要組員之間再討論一下呢？並確認一下你們小組的想法（邏輯）與說法（表達）是否一致？

**Comment by alvinzhan** [comment]
請問助教，這個方法是正確的嗎？？
因為是我們討論出來的結果。

**Comment by c910335** [comment]
演算法的部分基本上是沒有錯
不過有一些細節仍需注意

> 利用 while 迴圈（條件：i < m && j < n）。
> 先從 i = 0, j = 0 開始，將 x[i], y[j] 大的減小的存入 min。

有仔細看題目的話應該會注意到 index 是從 1 開始（這是老師的習慣
所以此段應修正為

> 利用 while 迴圈（條件：i <= m && j <= n）。
> 先從 i = 1, j = 1 開始，將 x[i], y[j] 大的減小的存入 min。

**Comment by c910335** [comment]
時間分析的部分

@jeremy1320  我很好奇你的「平均下來」是怎麼求出來的？
一般平均是總和除以數目求得。
但如果你已經知道總和了，何必去計算平均，再以平均求出解答。
那個總合就已經是答案了不是嗎？

再來，m 與 n 這兩個數分別是指 x 與 y 這兩個陣列的長度。
我不是很確定你是不是搞混了這些變數，
導致我們無法理解你想表達的內容。

> 平均下來，一個 m 會跟兩個 n 比到，一個 n 會跟兩個 m 比到。

@jeremy1320 這句話到底想說什麼可以請你解釋一下嗎？謝謝。

**Comment by scps940707** [comment]
演算法整體上是正確的，不過你們在時間分析上面有點問題。m是x陣列的元素數量，n是y陣列的元素數量，所以你們想要表達的是…？

**Comment by jeremy1320** [comment]
抱歉，我想我沒搞錯變數。但我不知道怎麼把我的想法轉換成文字。我們再討論看看。

**Comment by yachu123** [comment]
[演算法HW1.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1328316/HW1.pptx)

**Comment by alvinzhan** [comment]
因為迴圈中的i會跑m次 j會跑n次 雖然不是每次迴圈跑完都各加1 但最終每個陣列的元素一定都會走訪到 所以是O(m+n)

**Comment by c910335** [comment]
Bubble sort 的 i 會跑 n 次、j 會跑 n 次，最終每個元素一定都有走過，但是它的時間複雜度是 O(n<sup>2</sup>)。
那你的演算法為何不是 O(mn) 呢

**Comment by yachu123** [comment]
bubble sort 是兩層迴圈?
我們只使用一層?

**Comment by c910335** [comment]
只用一層迴圈並不是個充分的理由。
你覺得底下這個 pseudocode 的時間複雜度是多少？

```ruby
for i in 1..n^2
  # do something in constant time
```

**Comment by jeremy1320** [comment]
每次跑 while 迴圈的時候，都會有 i 或 j 往上 +1 。
所以最終 i = m, j = n 時，大約是 m+n 次。

**Comment by c910335** [comment]
解題概念的部分我看不太懂。

> 兩個排好的陣列相減的最小值

兩個排好的陣列要如何相減？
是總和相減嗎？還是當成集合找差集？

> 因為是排好的陣列所以前面比較過後的數不可能再小於後面比的數

前面的數不是應該比後面的數小嗎？（因為是排序過的陣列）
為何比較過後就不可能小於後面的數？

> Ex : 已知 x[2] 從 y[1] 到 y[6] 發現 |x[2]-y[6]|最小，那麼就不用考慮 x[1] 與 y[6]了

```
x = [6, 1000, 2000, 3000]
y = [1, 2, 3, 4, 5, 6]
```

x[2] (1000) 去跟 y[1] 到 y[6] 比發現 |x[2]-y[6]| 最小 (994)
那為何不用考慮 x[1] 與 y[6]？

**Comment by c910335** [comment]
@alvinzhan @jeremy1320 
時間分析的部分記得加到投影片

**Comment by jeremy1320** [comment]
[演算法HW1_ver2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1328427/HW1_ver2.pptx)

**Comment by c910335** [comment]
雖然你們解題概念講得不錯，
但是似乎沒看到演算法具體的步驟（除了沒人想看的程式碼

**Comment by yachu123** [comment]
請問助教演算法具體步驟是指?

**Comment by c910335** [comment]
就是你提了幾個概念卻沒有具體步驟，
把步驟藏在概念裡了。

**Comment by jeremy1320** [comment]
那如果是直接在程式碼加註解呢？

**Comment by alvinzhan** [comment]
如果在口頭報告的時候詳細的講步驟呢?會在簡報的第五頁講到。

**Comment by c910335** [comment]
> 利用 while 迴圈（條件：i <= m && j <= n）。
> 先從 i = 1, j = 1 開始，將 x[i], y[j] 大的減小的存入 min。
> 再將小的一往下一個，例：若 x[i] < y[j]，i++。
> 做到結束，若出現小於 min 的數，則取代。
> 中間若出現 x[i] = y[j]，則 min = 0，直接跳出迴圈結束。
> by 第九組

我覺得這講得很好啊
為什麼不寫進投影片呢

**Comment by alvinzhan** [comment]
好的!了解了~

**Comment by alvinzhan** [comment]
[HW1_ver3.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1330025/HW1_ver3.pptx)

**Comment by c910335** [comment]
@alvinzhan @jeremy1320 @yachu123
請到 #13 確認 p4.md
