### ISSUE TITLE
第二題

### ISSUE THREAD

**Issue by rogerchang23424** [NCU-CSIE-Algorithmics-A-1061/Homework-1#3]
第十六組負責

**Comment by rogerchang23424** [comment]
演算法是要寫出程式碼還是算試啊

**Comment by c910335** [comment]
用自然語言描述演算法即可。
如果你認為這樣不足以解釋，也可以附上 pseudocode。
請不要直接貼程式碼上來，謝謝。

**Comment by rogerchang23424** [comment]
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1327109/algorithm-problem2.pptx)

**Comment by c910335** [comment]
1. 結束條件

這答案大致上沒有問題，
不過你漏了一個對於演算法來說很重要的條件，
那就是「有限步驟」。
你並沒有說明演算法進行到什麼階段結束，
若是照著所述步驟進行，
那這做法永遠不會結束。

2. 時間複雜度

你所提出的時間複雜度乍看之下很有道理，
但是你是如何求得這時間複雜度的？

**Comment by rogerchang23424** [comment]
修改過的ppt
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1327135/algorithm-problem2.pptx)

**Comment by c910335** [comment]
1. 第一步不明確

> 首先先假設x的值(0<x<A)

這一步驟你做了假設 x 介於這個範圍之內，
但是得有明確的值才有辦法進行後續的步驟。

2. x<sub>n+1</sub> 與 x<sub>n</sub> 是指？

> 計算x<sub>n+1</sub> = (x<sub>n</sub>+A/x<sub>n</sub>)/2

n 是指題目的輸入這我沒問題，但 x<sub>n</sub> 是代表什麼意思？

3. x<sub>0</sub> 又是指？

最後一頁有 x<sub>0</sub>，
但是前一頁的做法並無提及。
所以 x<sub>0</sub> 到底？

**Comment by rogerchang23424** [comment]
有些地方忘了改
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1327222/algorithm-problem2.pptx)

**Comment by rogerchang23424** [comment]
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1327227/algorithm-problem2.pptx)

**Comment by c910335** [comment]
> 首先先假設x的值(0<x<A)

我說你的第一步依然不明確啊

**Comment by rogerchang23424** [comment]
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1327934/algorithm-problem2.pptx)

**Comment by c910335** [comment]
等等
題目的輸入是 N
可是你的解法完全沒有用到 N

**Comment by rogerchang23424** [comment]
抱歉，忘記注意題目，謝謝助教
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1328296/algorithm-problem2.pptx)

**Comment by c910335** [comment]
> 1.首先由工程師給定x的值，例如：x := 1, x:=N/2等

我想請問 x 到底要給什麼值？
我還是看不懂。

**Comment by c910335** [comment]
問一下你的做法是建立在電腦整數運算的基礎上對吧？
（因為浮點數會耗費更多時間才會走到 `y = x` 而且跑完也不會是整數

**Comment by hallmoney** [comment]
再次修正過後的
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1328641/algorithm-problem2.pptx)

**Comment by c910335** [comment]
根據你的解法跑了一些計算之後，
請問答案在哪裡呢？

**Comment by hallmoney** [comment]
只要y和x之間誤差超級小,那y和x整數部分一定一樣,取x的整數部分就是N開根號所要的答案

**Comment by c910335** [comment]
> 只要y和x之間誤差超級小,那y和x整數部分一定一樣,取x的整數部分就是N開根號所要的答案

你不覺得這句話應該寫在投影片裡嗎

**Comment by hallmoney** [comment]
[algorithm-problem2.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1328769/algorithm-problem2.pptx)

**Comment by c910335** [comment]
@hallmoney @rogerchang23424
還請去 #11 確認一下

**Comment by rogerchang23424** [comment]
OK，已經確認過了，謝謝助教
