### ISSUE TITLE
第五題

### ISSUE THREAD

**Issue by imcool9514** [NCU-CSIE-Algorithmics-A-1061/Homework-1#7]
[第五題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1327183/default.pptx)

**Comment by c910335** [comment]
> = (k-1)n – 1(2<sup>k-1</sup>-1) / (2-1)  + 2<sup>k-1</sup> T(2)
> = (lg<sub>2</sub>n )n – 1(n/2-1) / (2-1)  + (n/2) T(2)

k - 1 是怎麼變成 lg<sub>2</sub>n 的？

**Comment by imcool9514** [comment]
做投影片照計算紙打時打錯，已修正該行。感謝助教提醒~

**Comment by c910335** [comment]
@imcool9514 
麻煩去 #8 確認一下

**Comment by imcool9514** [comment]
@c910335 
好的，已經確認過，謝謝助教了 : )
