### ISSUE TITLE
第一題

### ISSUE THREAD

**Issue by woodyhoko** [NCU-CSIE-Algorithmics-A-1061/Homework-1#9]
第十四組負責

**Comment by woodyhoko** [comment]
[第一題_第十四組.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1328693/_.pptx)

**Comment by woodyhoko** [comment]
有時間的看一下，有問題就直接修改吧！
時間太多者，請多加插圖以解釋得更清楚喔！

**Comment by c910335** [comment]
Quick sort 經常被描述成是 in-place 的排序演算法，
但實際上並不是，
至於理由你們再仔細想想看吧。

**Comment by woodyhoko** [comment]
請問您是助教嗎？如果是，我就跟您仔細討論，如果不是，自己想想(加油)。

**Comment by c910335** [comment]
留言的右上角有 `Owner` 或是 `Member` 的就是助教

**Comment by woodyhoko** [comment]
助教，失禮了，用手機版的看似乎沒有這項資訊，當初還認為是他組的多管閒事...lol

**Comment by woodyhoko** [comment]
Quick sort有很多種版本，而最經典的那種可以利用所謂的三方互換來排序。三方互換所需的額外資源甚至連常數集都不到（可做到，會較耗時耗力）

**Comment by woodyhoko** [comment]
如果為了追求純粹的快速，有人就會使用列表整理（須額外記憶體）來做分堆，也因此可稱之為out of place，但實則可以不用那種方法來達到同樣的成果

**Comment by woodyhoko** [comment]
如果是擔心因多段數列而造成額外的記憶體需求，則不用擔心。因為連merge sort都有in-place版本，可能有常數級的額外需求（標點），遞迴也需要ln(n)額外的記憶體才能追回主函式，因此總蓋而言還是屬於in-place

**Comment by c910335** [comment]
> 三方互換所需的額外資源甚至連常數集都不到

不到常數級是不可能的。
紀錄 pivot 的指標需要空間，
陣列分成兩半之後紀錄兩邊的位置及大小也需要空間，
要交換的時候連紀錄要交換的位置的空間都沒有我認為是不太可能。
如果你真的發明了不需任何額外空間的 Quick sort，
我建議你去領圖靈獎。

**Comment by c910335** [comment]
> 因為連merge sort都有in-place版本，可能有常數級的額外需求（標點），遞迴也需要ln(n)額外的記憶體才能追回主函式，因此總蓋而言還是屬於in-place

1. Merge sort 有 in-place 版本不代表 Quick sort 有
2. ln(n) 並不是常數級
3. 所以 in-place 的理由是？

**Comment by c910335** [comment]
> 助教，失禮了，用手機版的看似乎沒有這項資訊，當初還認為是他組的多管閒事...lol

我在 LMS 的公告也說了「未被分配到作業的同學也歡迎至各 Issue 底下參與討論」，
就算是其他組來留言，
我也不希望你認為他們多管閒事。

**Comment by woodyhoko** [comment]
>不到常數級是不可能的。
>紀錄 pivot 的指標需要空間，
>陣列分成兩半之後紀錄兩邊的位置及大小也需要空間，
>要交換的時候連紀錄要交換的位置的空間都沒有我認為是不太可能。
>如果你真的發明了不需任何額外空間的 Quick sort，
>我建議你去領圖靈獎。

交換事可以做到 0 額外空間的，因此3-way-swap也能夠做到。
遞迴程式(演算法)的確需要額外ln(n)級數的空間(有提過)，但是那是使用stack space 而非 heap space。
哈哈，如果真的能夠想出完全不需額外空間的演算法，那當然是太棒了，可惜我只是查察資料而已...

**Comment by woodyhoko** [comment]
>1. Merge sort 有 in-place 版本不代表 Quick sort 有
>2. ln(n) 並不是常數級
>3. 所以 in-place 的理由是？

謝謝提醒！經調查才發現Kronrod merge遠比想像中的複雜，的確無法直接延伸至Quick sort。
Kronrod merge 的時間複雜度是O(n*ln(n)^2)，而空間複雜度則成功的降低至常數級。
而Quick sort 額外的空間複雜度是ln(n)，也因此可能真的不能稱之為in-place？
還是說因為ln(n)的空間複雜度已經夠小了，因此也能符合定義呢？(wiki)
亦有可能是因為遞迴所使用到的stack 空間導致的ln(n)遠比heap 空間的需求還要小呢？
如果依照wiki與mit的教材，quick sort是in-place；但也查到某大學(mtu)主張quick sort並不是真正的in-place。(http://www.csl.mtu.edu/cs2321/www/newLectures/11_Quick_Sort.html)
所以我也不知道哪個定義才是真的了...

**Comment by woodyhoko** [comment]
>我在 LMS 的公告也說了「未被分配到作業的同學也歡迎至各 Issue 底下參與討論」，
>就算是其他組來留言，
>我也不希望你認為他們多管閒事。

沒留意到...對不起了。
好的！我也很樂意討論，知道了是這種氣氛設定我一定會踴躍參與加入討論的！

**Comment by woodyhoko** [comment]
經過了助教的提醒後，我修正了錯誤的地方。
謝謝助教

**Comment by woodyhoko** [comment]
[P1_Group14.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1329510/P1_Group14.pptx)

**Comment by woodyhoko** [comment]
[P1_Group14.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1329527/P1_Group14.pptx)

**Comment by c910335** [comment]
想請教你**三方互換**（3-way-swap）指的是哪件事？

**Comment by woodyhoko** [comment]
>想請教你三方互換（3-way-swap）指的是哪件事？

就只是A,B,C變成B,C,A或C,A,B。
兩者互換可以靠xor來達到不須第三個變數，同概念用三次就能完成三方互換。

**Comment by c910335** [comment]
看你一直強調三方互換，但是 Quick sort 好像沒有什麼特別需要用到這個的地方？

**Comment by woodyhoko** [comment]
我看的版本是只使用這種方法來找精準度應該到的位置，並沒有特別強調啦～
如果是另一個作法，則整理後還要加一個把基準點插入的動作，我純粹只是懶得多考慮或描述這步驟而使用三方互換的版本罷了

**Comment by c910335** [comment]
@woodyhoko 我今天提的部分你要更新一下嗎？

**Comment by woodyhoko** [comment]
是的，好啊！
[P1_Group14.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1331899/P1_Group14.pptx)

**Comment by c910335** [comment]
我的錯，
Quick sort 遞迴時可以多一個判斷先走小的那邊，
另一邊在用你說的尾遞迴優化掉，
可以做到 Worst Case 只需 O(log(n)) 的額外空間。
不過我還是比較喜歡 in-place 比較嚴格的定義。

**Comment by scps940707** [comment]
> 沒留意到...對不起了。
> 好的！我也很樂意討論，知道了是這種氣氛設定我一定會踴躍參與加入討論的！

你以為你在玩ＲＰＧ嗎？我還世界觀設定哩！無論什麼情況下都要懂得share unserstanding好嗎？
即使身為助教也是虛心在學習，所以你也不要有自我優越感，謝謝！

**Comment by woodyhoko** [comment]
...我毫無您所說的意思，只是一開始誤會以為這裡只是作業繳交區。

這是更改過的版本。
[P1_Group14.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1378408/P1_Group14.pptx)

**Comment by c910335** [comment]
@woodyhoko 請到 #15 確認
